dist: xenial   # required for Python >= 3.7
language: python

# List the versions of Python you'd like to test against
python:
  - 3.7
  - 3.8

# Setup DB
services:
  - postgresql

# Tell Travis the things it will need to install when it boots
install:
   # Install the dependencies the app itself has
   # which in this case I choose to keep in a requirements files
 - pip install -r requirements/base.txt
 - pip install -r requirements/testing.txt

before_script:
 - psql -c 'create database "pricelist-test";' -U postgres

# Tell Travis how to run the test script itself
script: DB_USER=postgres DB_PASSWORD="" PYTHONPATH=server py.test --cov=server tests/unit_tests/

after_success: coveralls
